<a href="https://colab.research.google.com/github/bear4o4/Python_First_Try/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 4 - Numpy Operations**
>
> In this assignment you will:
>
> 1. Provide explanation and usage of 5 numpy functions given below.
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 2 examples for each function).
> 3. Adding explaination for each function is mandatory.

Functions:

- np.concatenate()
- np.dot()
- np.linalg.det()
- np.random.rand()
- np.where()


In [ ]:
import numpy as np

## Function 1 - np.concatenate

this function is used to combine two or more array along a certain or fixed axis

In [ ]:
# Example 1
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = np.concatenate((x, y))
print("Concatenated array: ", z)

Concatenated array:  [1 2 3 4 5 6]


here there are two arrays and they will combine to form one single array

In [ ]:
# Example 2
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.array([[9, 10], [11, 12]])


a = np.concatenate((x, y, z))

print("Concatenated array: ", a)

Concatenated array:  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


here we have 3 arrays which are 2x2 and now it will all be combined

## Function 2 - np.dot()

this function provide with dot product of two arrays


In [ ]:
# Example 1 -
a = np.array([1, 2])
b = np.array([3, 4])


ans = np.dot(a, b)

print(" dot product is: ", ans)

 dot product is:  11


here we combining and getting the dot product of two arrays

In [ ]:
# Example 2 -
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])


ans = np.dot(m1, m2)

print(ans)

[[19 22]
 [43 50]]


here we have two matrics of whom we are taking dot product

## Function 3 - np.linalg.det()

this python functio calculates the determinant of a square maatrix , it is often used in linear alegbra to commute certain properties of mtrix and its equations

In [ ]:
# Example 1 -
m = np.array([[1, 2], [3, 4]])


determinant = np.linalg.det(m)

print(determinant)

-2.0000000000000004


here we have computed the determinant of a 2x2 matrix

In [ ]:
# Example 2 -
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


determinant = np.linalg.det(m)

print(determinant)

0.0


here i have shown that the determinant of 3x3 matrix can also be worked on by this function

## Function 4 - np.random.rand()

this function generates random values from uniform distribution over the interval [0,1]

In [ ]:
# Example 1 -

rm= np.random.rand(5)

print(rm)

[0.74948496 0.75239253 0.96641069 0.79314788 0.86598857]


Explanation about example:here it shows how to generate 1D array of random numbers

In [ ]:
# Example 2 -

rm = np.random.rand(3, 3)

print(rm)

[[0.20317862 0.82799908 0.03447742]
 [0.75745574 0.47435523 0.93296272]
 [0.01338353 0.12065224 0.16054861]]


here it shows a 2d array of random values

## Function 5 - np.where()

this function returns the indices of the values in the given array

In [ ]:
# Example 1 -
n = np.array([1, 5, 8, 2, 7, 4, 6, 9, 3, 0])


sn = np.where(n > 5)

print(sn)

(array([2, 4, 6, 7]),)


Explanation about example: here it  has selected elements from an array based on a condition

In [ ]:
# Example 2 -
n1 = np.array([1, 2, 3, 4, 5])
n2 = np.array([6, 7, 8, 9, 10])


sn = np.where([True, True, False, False, False], n1, n2)

print(sn)

[ 1  2  8  9 10]


here it shows how to use this functio to select elements from two arrays base of conditions

## Submission

Congratulations on making it this far! You've reached the end of this part of the assignment.

* Don't forget to run all the cell before the submission. <br/>
* Download this file as `.ipynb` and rename it as `RollNumber_Numpy.ipynb`
